---
name: Chi-Kuang
surname: Yeh
position: "CANSSI Distinguish Postdoctoral Fellow"
address: "Department of Statistics and Actuarial Science \nUniversity of Waterloo"
www: chikuang.github.io
email: "chi-kuang.yeh@uwaterloo.ca"
twitter: chikuang_y
github: chikuang
linkedin: chikuang
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Research interest
  1. Functional data analysis
  2. Time series analysis
  3. Longitudinal data analysis
  4. Dependence modelling

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~Supervisor, ~Thesis,
  "PhD in Statisitcs", "2018-2023", "University of Waterloo", "ON, Canada", "Gregory  Rice & Joel A. Dubin", "Methods in Functional Data Analysis: Forecast Evaluation, Robust Serial Dependence Measures, and a Spatial Factor Copula Model",
  #
  "MSc in Statisitcs", "2016-2018", "University of Victoria", "BC, Canada", "Julie Zhou", "Optimal Regression Design under Second-order Least Squares Estimator: Theory, Algorithm and Applications",
  #
  "BSc (H.) in combined Mathematics and Statistics", "2013-2016", "University of Victoria", "BC, Canada", "Julie Zhou", "NA"
) %>% 
  detailed_entries(glue::glue("{Degree}, Advisor: {Supervisor}"), Year, Institution, Where, glue::glue("Disseration: {Thesis}"))
```

# Selected awards

```{r}
tribble(
  ~Year, ~Desc, ~Issuer,
  "2022-2023", "Ontario Graduate Scholarship", "Government of Ontario",
  "2022-2023", "Ontario Graduate Scholarship", "Government of Ontario",
  "2020-2023", "President Scholarship", "University of Waterloo",
  "2021 Apr", "Statistics and Actaurial Science Chair's Award", "University of Waterloo",
  "2018 Jun", "Student Travel Award", "Statistical Society of Canada",
  "2018",  "Graduate Student Conference Travel Grant", "University of Victoria",
  "2018 Apr", "CUPE Conference Travel Award", "University of Victoria",
  "2017", "Florence and Wallace Wilkinson Memorial Award", "University of Victoria",
  "2017-2018", "Faculty of Graduate Studies Scholarship", "University of Victoria",
  "2016", "University Scholarship", "University of Victoria",
  "2010", "Summit Entrance Scholarship", "Simon Fraser University"
) %>% 
  brief_entries(
    # glue::glue("Nobel Prize in {Type}"),
    Desc,
    Year, 
    Issuer
  )
```

# Publications

```{r}
library(dplyr)
bibliography_entries("packages.bib") %>%
  arrange(issued, desc(author$family))
```

